
name: poll live twitch streamers

on:
  schedule:
    - cron: "*/30 * * * *"
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: publish messages if live
    steps:
    - name: git co
      uses: actions/checkout@v2
    - name: call lil script
      env:
        CLIENT_ID: ${{ secrets.LAGGY_BOT_CLIENT_ID }}
        OAUTH: ${{ secrets.LAGGY_BOT_OAUTH }}
        DISCORD_WEBHOOK: ${{ secrets.LAGGY_BOT_DISCORD_HOOK }}
      run: ./poll.sh
